# use official Ubuntu base image
FROM ubuntu:22.04

# avoid prompts durng apt installs
ENV DEBIAN_FORNTEND=noninteractive

# install system dependencies
RUN apt-get update && apt-get install -y \
    git wget unzip build-essential \ 
    cmake libssl-dev libusb-1.0-0-dev \
    libudev-dev libglu1-mesa-dev \
    libgtk-3-dev pkg-config \
    libglfw3-dev libgl1-mesa-dev \
    python3.10 python3.10-dev python3.10-venv python3-pip \
    && apt-get clean

# install udev rules for Realsense
RUN apt-get update && apt-get install -y curl udev \
    && mkdir -p /etc/udev/rules.d \
    && curl -fsSL https://raw.githubusercontent.com/IntelRealSense/librealsense/master/config/99-realsense-libusb.rules \
    -o /etc/udev/rules.d/99-realsense-libusb.rules

# build librealsense2 from source
WORKDIR /tmp
RUN git clone https://github.com/IntelRealSense/librealsense.git -b v2.54.1
WORKDIR /tmp/librealsense
RUN mkdir build && cd build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Release -DUILD_PYTHON_BINDINGS=ON \
              -DPYTHON_EXECUTABLE=/usr/bin/python3.10 && \
    make -j$(nproc) && make install && ldconfig

# create python virtual environment
RUN python3.10 -m venv /my
ENV PATH="/my/bin:$PATH"

# install python dependencies
COPY requirements.txt /workspace/requirements.txt
RUN pip install --upgrade pip && pip install -r /workspace/requirements.txt

# copy demp script
COPY stream_realsense.py /workspace/stream_realsense.py

# set working directory
WORKDIR /workspace

# set default command
CMD ["python", "stream_realsense.py"]
