name: my
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pandas
  - opencv
  - jupyter
  - pip:
      - torch
      - torchvision
      - tqdm
      - seaborn
      - PyYAML
